name: aplikasi_makanan
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/food_bg.jpg
  # Kalau ada assets, tambahkan di sini:
  # assets:
  #   - assets/nasigoreng.jpg
  #   - assets/jus.jpg
